tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"
brew "bash"
brew "git"
brew "yarn", args: ["without-node"]
brew "zsh"
brew "zsh-completions"
cask "google-chrome"
cask "firefox"
cask "iterm2"
cask "visual-studio-code"
cask "slack"
cask "spotify"
